// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV9Me56_KdvleiA_OROWkRR3M449JZLdc',
    appId: '1:464598078345:web:8d9c28ee66786a201bc758',
    messagingSenderId: '464598078345',
    projectId: 'messagesapp-cf8ee',
    authDomain: 'messagesapp-cf8ee.firebaseapp.com',
    storageBucket: 'messagesapp-cf8ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKygS4HexiSFB5o8m57HyiyPdPqAKg3j4',
    appId: '1:464598078345:android:5c04cbe9974aabb71bc758',
    messagingSenderId: '464598078345',
    projectId: 'messagesapp-cf8ee',
    storageBucket: 'messagesapp-cf8ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxPsRJ1-Q3lTfPzIIpZg92AnpE8q7sNfA',
    appId: '1:464598078345:ios:7777e5aa01189ea91bc758',
    messagingSenderId: '464598078345',
    projectId: 'messagesapp-cf8ee',
    storageBucket: 'messagesapp-cf8ee.appspot.com',
    iosBundleId: 'com.example.myProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxPsRJ1-Q3lTfPzIIpZg92AnpE8q7sNfA',
    appId: '1:464598078345:ios:f32fb2eebc38a2d41bc758',
    messagingSenderId: '464598078345',
    projectId: 'messagesapp-cf8ee',
    storageBucket: 'messagesapp-cf8ee.appspot.com',
    iosBundleId: 'com.example.myProject1.RunnerTests',
  );
}
